# Роли: Администрация Города
# Сумки (и пояс/РПС у Стражи) выдаются через выбор снаряжения — см. Loadouts/loadouts.yml.

- type: job
  id: DystopiaConsul
  name: job-name-dystopia-consul
  description: job-description-dystopia-consul
  playTimeTracker: JobDystopiaConsul
  startingGear: DystopiaConsulGear
  icon: "JobIconDystopiaConsul"
  supervisors: job-supervisors-nobody
  joinNotifyCrew: true
  accessGroups:
  - DystopiaAll
  # ВРЕМЕННО: ванильные доступы для дверей тестовой карты Terra. Убрать вместе с Terra.
  - AllAccess

- type: startingGear
  id: DystopiaConsulGear
  equipment:
    jumpsuit: DystopiaClothingUniformConsul
    outerClothing: DystopiaClothingOuterConsulJacket
    neck: DystopiaClothingNeckConsulCloak
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesColorWhite
    id: DystopiaConsulPDA
    ears: ClothingHeadsetAltDystopiaConsul
    pocket1: WeaponPistolMk58
  storage:
    back:
    - MagazinePistol
    - RubberStampCaptain
    - Pen

- type: job
  id: DystopiaAdjutant
  name: job-name-dystopia-adjutant
  description: job-description-dystopia-adjutant
  playTimeTracker: JobDystopiaAdjutant
  startingGear: DystopiaAdjutantGear
  icon: "JobIconDystopiaAdjutant"
  supervisors: dystopia-job-supervisors-command
  access:
  - DystopiaAdministration
  - DystopiaGuard
  - DystopiaPatrol
  - DystopiaSanitary
  - DystopiaScience
  # ВРЕМЕННО: ванильные доступы для дверей тестовой карты Terra. Убрать вместе с Terra.
  - Command
  - Maintenance
  - External
  - Lawyer

- type: startingGear
  id: DystopiaAdjutantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCommandGeneric
    mask: DystopiaClothingMaskGasSanitary
    shoes: ClothingShoesBootsLaceup
    id: DystopiaAdjutantPDA
    ears: ClothingHeadsetDystopiaAdministration
    pocket1: Pen
  storage:
    back:
    - Paper
    - Paper
    - Paper

- type: job
  id: DystopiaCivilInspector
  name: job-name-dystopia-civil-inspector
  description: job-description-dystopia-civil-inspector
  playTimeTracker: JobDystopiaCivilInspector
  startingGear: DystopiaCivilInspectorGear
  icon: "JobIconDystopiaCivilInspector"
  supervisors: dystopia-job-supervisors-consul
  joinNotifyCrew: true
  accessGroups:
  # ВРЕМЕННО: ванильные доступы для дверей тестовой карты Terra. Убрать вместе с Terra.
  - Service
  - Cargo
  access:
  - DystopiaAdministration
  - DystopiaInspection
  - DystopiaGates
  - DystopiaFactory
  - DystopiaGreenhouse
  - DystopiaCanteen
  - DystopiaTavern
  - DystopiaShop
  # ВРЕМЕННО: ванильные доступы для дверей тестовой карты Terra. Убрать вместе с Terra.
  - Command
  - HeadOfPersonnel
  - Maintenance

- type: startingGear
  id: DystopiaCivilInspectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    mask: DystopiaClothingMaskGasSanitary
    shoes: ClothingShoesColorBrown
    id: DystopiaCivilInspectorPDA
    ears: ClothingHeadsetAltDystopiaAdministration
    pocket1: Pen
  storage:
    back:
    - RubberStampHop
    - Paper
    - Paper
