# Роли: Горожане
# Сумки (и пояс/РПС у Стражи) выдаются через выбор снаряжения — см. Loadouts/loadouts.yml.

- type: job
  id: DystopiaProletarian
  name: job-name-dystopia-proletarian
  description: job-description-dystopia-proletarian
  playTimeTracker: JobDystopiaProletarian
  startingGear: DystopiaProletarianGear
  icon: "JobIconDystopiaProletarian"
  supervisors: dystopia-job-supervisors-inspector
  access:
  # ВРЕМЕННО: ванильные доступы для дверей тестовой карты Terra. Убрать вместе с Terra.
  - Maintenance

- type: startingGear
  id: DystopiaProletarianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    mask: ClothingMaskGas
    shoes: ClothingShoesColorBlack
    id: DystopiaProletarianPDA
    ears: ClothingHeadsetGrey

- type: job
  id: DystopiaShopkeeper
  name: job-name-dystopia-shopkeeper
  description: job-description-dystopia-shopkeeper
  playTimeTracker: JobDystopiaShopkeeper
  startingGear: DystopiaShopkeeperGear
  icon: "JobIconDystopiaShopkeeper"
  supervisors: dystopia-job-supervisors-inspector
  access:
  - DystopiaShop
  # ВРЕМЕННО: ванильные доступы для дверей тестовой карты Terra. Убрать вместе с Terra.
  - Cargo
  - Maintenance

- type: startingGear
  id: DystopiaShopkeeperGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCargo
    mask: ClothingMaskGas
    shoes: ClothingShoesColorBrown
    id: DystopiaShopkeeperPDA
    ears: ClothingHeadsetCargo
