// SPDX-License-Identifier: AGPL-3.0-or-later
// Dystopia: анализатор здоровья — кукла частей тела поверх спрайта пациента и вкладки «Тело / Органы / Химикаты».
// Справа — «Состояние»: найденные проблемы. Данные о частях, ранах, органах и химикатах читаются на клиенте —
// всё это приходит по сети вместе с телом пациента; сервер присылает только общие показатели (температура, кровь).

using System.Linq;
using System.Numerics;
using Content.Shared._Dystopia.Health.Medical.Surgery.Wounds;
using Content.Shared._Dystopia.Health.Medical.Surgery.Wounds.Components;
using Content.Shared._Dystopia.Health.Medical.Surgery.Wounds.Systems;
using Content.Shared._Dystopia.Health.Medical.Surgery.Traumas;
using Content.Shared._Dystopia.Health.Medical.Surgery.Traumas.Components;
using Content.Shared._Dystopia.Health.Medical.Surgery.Traumas.Systems;
using Content.Shared._Dystopia.Health.Targeting;
using Content.Shared.Atmos;
using Content.Shared.Atmos.Rotting;
using Content.Shared.Body;
using Content.Shared.Body.Part;
using Content.Shared.Body.Systems;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.Damage.Systems;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Dystopia.Health.UserInterface.HealthAnalyzer;

[GenerateTypedNameReferences]
public sealed partial class DystopiaHealthAnalyzerPanel : BoxContainer
{
    private enum Mode : byte { Body, Organs, Chemicals }

    private readonly IEntityManager _entityManager;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    private readonly SpriteSystem _spriteSystem;
    private readonly DamageableSystem _damageable;
    private readonly SharedBodySystem _body;
    private readonly BodySystem _organs;
    private readonly WoundSystem _wounds;
    private readonly SharedSolutionContainerSystem _solutions;
    private readonly TraumaSystem _traumas;

    private readonly Dictionary<TargetBodyPart, TextureButton> _buttons;
    private readonly Dictionary<TargetBodyPart, TextureRect> _statusLayers;
    private TargetBodyPart? _hovered;

    private static readonly Color HighlightColor = Color.FromHex("#9FD7FF");

    private HealthAnalyzerUiState? _state;
    private EntityUid? _target;
    private TargetBodyPart? _selected;
    private Mode _mode = Mode.Body;

    public DystopiaHealthAnalyzerPanel()
    {
        RobustXamlLoader.Load(this);

        _entityManager = IoCManager.Resolve<IEntityManager>();
        _prototypes = IoCManager.Resolve<IPrototypeManager>();
        _cache = IoCManager.Resolve<IResourceCache>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _damageable = _entityManager.System<DamageableSystem>();
        _body = _entityManager.System<SharedBodySystem>();
        _organs = _entityManager.System<BodySystem>();
        _wounds = _entityManager.System<WoundSystem>();
        _solutions = _entityManager.System<SharedSolutionContainerSystem>();
        _traumas = _entityManager.System<TraumaSystem>();

        _buttons = new Dictionary<TargetBodyPart, TextureButton>
        {
            { TargetBodyPart.Head, HeadButton },
            { TargetBodyPart.Chest, ChestButton },
            { TargetBodyPart.Groin, GroinButton },
            { TargetBodyPart.LeftArm, LeftArmButton },
            { TargetBodyPart.LeftHand, LeftHandButton },
            { TargetBodyPart.RightArm, RightArmButton },
            { TargetBodyPart.RightHand, RightHandButton },
            { TargetBodyPart.LeftLeg, LeftLegButton },
            { TargetBodyPart.LeftFoot, LeftFootButton },
            { TargetBodyPart.RightLeg, RightLegButton },
            { TargetBodyPart.RightFoot, RightFootButton },
        };

        _statusLayers = new Dictionary<TargetBodyPart, TextureRect>
        {
            { TargetBodyPart.Head, StatusHead },
            { TargetBodyPart.Chest, StatusChest },
            { TargetBodyPart.Groin, StatusGroin },
            { TargetBodyPart.LeftArm, StatusLeftArm },
            { TargetBodyPart.LeftHand, StatusLeftHand },
            { TargetBodyPart.RightArm, StatusRightArm },
            { TargetBodyPart.RightHand, StatusRightHand },
            { TargetBodyPart.LeftLeg, StatusLeftLeg },
            { TargetBodyPart.LeftFoot, StatusLeftFoot },
            { TargetBodyPart.RightLeg, StatusRightLeg },
            { TargetBodyPart.RightFoot, StatusRightFoot },
        };

        foreach (var (part, button) in _buttons)
        {
            button.MouseFilter = MouseFilterMode.Stop;
            button.OnMouseEntered += _ => { _hovered = part; UpdateDollHighlight(); };
            button.OnMouseExited += _ => { if (_hovered == part) _hovered = null; UpdateDollHighlight(); };
            button.OnPressed += _ =>
            {
                _selected = part;
                _mode = Mode.Body;
                Refresh();
            };
        }

        ReturnButton.OnPressed += _ =>
        {
            _selected = null;
            Refresh();
        };

        BodyButton.OnPressed += _ => SetMode(Mode.Body);
        OrgansButton.OnPressed += _ => SetMode(Mode.Organs);
        ChemicalsButton.OnPressed += _ => SetMode(Mode.Chemicals);
    }

    private void SetMode(Mode mode)
    {
        _mode = mode;
        if (mode != Mode.Body)
            _selected = null;
        Refresh();
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);
        if (target != _target)
        {
            _selected = null;
            _mode = Mode.Body;
        }

        _state = state;
        _target = target;
        Refresh();
    }

    private void Refresh()
    {
        if (_state is not { } state || _target is not { } target || !_entityManager.EntityExists(target) ||
            !_entityManager.TryGetComponent<DamageableComponent>(target, out _))
        {
            NoPatientDataText.Visible = true;
            PatientDataContainer.Visible = false;
            return;
        }

        NoPatientDataText.Visible = false;
        PatientDataContainer.Visible = true;

        SetupHeader(target, state);

        var humanoid = _entityManager.HasComponent<TargetingComponent>(target);
        PartView.Visible = humanoid;
        StatusDoll.Visible = humanoid && SpriteViewAllowed(state);
        SpriteView.Visible = !humanoid && SpriteViewAllowed(state);
        NoDataTex.Visible = !SpriteViewAllowed(state);
        if (humanoid)
            UpdateStatusDoll(target);
        OrgansButton.Disabled = !humanoid;
        BodyButton.Pressed = _mode == Mode.Body;
        OrgansButton.Pressed = _mode == Mode.Organs;
        ChemicalsButton.Pressed = _mode == Mode.Chemicals;
        UpdateDollHighlight();

        GroupsContainer.RemoveAllChildren();
        ConditionsListContainer.RemoveAllChildren();

        switch (_mode)
        {
            case Mode.Body:
                PopulateBody(target, state);
                break;
            case Mode.Organs:
                PopulateOrgans(target);
                break;
            case Mode.Chemicals:
                PopulateChemicals(target);
                break;
        }

        if (ConditionsListContainer.ChildCount == 0)
            AddCondition(Loc.GetString("condition-none"));
    }

    /// <summary>Наведённая или выбранная часть подсвечивается на кукле.</summary>
    private void UpdateDollHighlight()
    {
        foreach (var (part, layer) in _statusLayers)
        {
            layer.Modulate = part == _hovered || part == _selected ? HighlightColor : Color.White;
        }
    }

    /// <summary>Кукла состояния: каждая часть окрашена по своему состоянию (как кукла под оповещениями).</summary>
    private void UpdateStatusDoll(EntityUid target)
    {
        foreach (var (part, severity) in _wounds.GetWoundableStatesOnBody(target))
        {
            if (!_statusLayers.TryGetValue(part, out var layer))
                continue;

            var name = part.ToString().ToLowerInvariant();
            var rsi = new SpriteSpecifier.Rsi(
                new ResPath($"/Textures/_Dystopia/Health/Interface/Targeting/Status/{name}.rsi"),
                $"{name}_{(int) severity}");
            layer.Texture = _spriteSystem.Frame0(rsi);
        }
    }

    // ===================== Шапка =====================

    private void SetupHeader(EntityUid target, HealthAnalyzerUiState state)
    {
        ScanModeLabel.Text = state.ScanMode.HasValue
            ? state.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");
        ScanModeLabel.FontColorOverride = state.ScanMode.HasValue && state.ScanMode.Value ? Color.Green : Color.Red;

        SpriteView.SetEntity(target);

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(Identity.Name(target, _entityManager));
        NameLabel.SetMessage(name);

        SpeciesLabel.Text = _entityManager.TryGetComponent<HumanoidProfileComponent>(target, out var humanoid)
            ? Loc.GetString(_prototypes.Index(humanoid.Species).Name)
            : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        TemperatureLabel.Text = !float.IsNaN(state.Temperature)
            ? $"{state.Temperature - Atmospherics.T0C:F1} °C ({state.Temperature:F1} K)"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        BloodLabel.Text = !float.IsNaN(state.BloodLevel)
            ? $"{state.BloodLevel * 100:F1} %"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        StatusLabel.Text = _entityManager.TryGetComponent<MobStateComponent>(target, out var mobState)
            ? GetStatus(mobState.CurrentState)
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        // Тревоги (как у ванильного анализатора)
        var showAlerts = state.Unrevivable == true || state.Bleeding == true;
        AlertsDivider.Visible = showAlerts;
        AlertsContainer.Visible = showAlerts;
        AlertsContainer.RemoveAllChildren();
        if (state.Unrevivable == true)
            AlertsContainer.AddChild(new RichTextLabel { Text = Loc.GetString("health-analyzer-window-entity-unrevivable-text"), Margin = new Thickness(0, 4), MaxWidth = 300 });
        if (state.Bleeding == true)
            AlertsContainer.AddChild(new RichTextLabel { Text = Loc.GetString("health-analyzer-window-entity-bleeding-text"), Margin = new Thickness(0, 4), MaxWidth = 300 });
    }

    // ===================== Тело =====================

    private void PopulateBody(EntityUid target, HealthAnalyzerUiState state)
    {
        var partId = _selected is { } sel ? _body.GetTargetedPartEntity(target, sel) : null;
        var isPart = _selected != null;

        ReturnButton.Visible = isPart;
        PartNameLabel.Visible = isPart;
        DamageLabelHeading.Visible = true;
        DamageLabel.Visible = true;

        var humanoid = _entityManager.HasComponent<TargetingComponent>(target);
        DamageLabelHeadingVital.Visible = humanoid;
        DamageLabelVital.Visible = humanoid;
        if (humanoid)
            DamageLabelVital.Text = VitalDamage(target).ToString();

        if (isPart)
        {
            PartNameLabel.Text = partId != null
                ? Identity.Name(partId.Value, _entityManager)
                : Loc.GetString("health-analyzer-parts-missing-name", ("part", PartName(_selected!.Value)));

            var perType = new Dictionary<string, FixedPoint2>();
            if (partId != null && _entityManager.TryGetComponent<WoundableComponent>(partId, out var woundable))
            {
                foreach (var wound in _wounds.GetWoundableWounds(partId.Value, woundable))
                {
                    if (wound.Comp.IsScar || wound.Comp.WoundVisibility == WoundVisibility.AdvancedScanner)
                        continue;

                    var type = wound.Comp.DamageType.Id;
                    perType[type] = perType.GetValueOrDefault(type) + wound.Comp.WoundSeverityPoint;
                }
            }

            DamageLabel.Text = perType.Values.Aggregate(FixedPoint2.Zero, (a, b) => a + b).ToString();
            DrawDiagnosticGroups(GroupBy(perType), perType);
        }
        else
        {
            DamageLabel.Text = _damageable.GetTotalDamage(target).ToString();
            var perType = _damageable.GetAllDamage(target).DamageDict
                .ToDictionary(kv => kv.Key.Id, kv => kv.Value);
            var groups = _damageable.GetDamagePerGroup(target)
                .OrderByDescending(d => d.Value)
                .ToDictionary(x => x.Key.Id, x => x.Value);
            DrawDiagnosticGroups(groups, perType);
        }

        // «Состояние»
        var entityName = Identity.Name(target, _entityManager);
        if (state.Unrevivable == true)
            AddCondition(Loc.GetString("condition-body-unrevivable", ("entity", entityName)));
        if (state.Bleeding == true)
            AddCondition(Loc.GetString("condition-body-bleeding", ("entity", entityName)));

        // Боль (всё тело)
        if (!isPart && _entityManager.TryGetComponent<Content.Shared._Dystopia.Health.Medical.Pain.PainComponent>(target, out var pain))
        {
            if (pain.Level != Content.Shared._Dystopia.Health.Medical.Pain.PainLevel.None)
                AddCondition(Loc.GetString($"condition-pain-{pain.Level}", ("pain", (int) pain.Pain)));
            if (pain.Suppression >= 5f)
                AddCondition(Loc.GetString("condition-pain-suppressed", ("amount", (int) pain.Suppression)));
        }

        // Зависимость и ломка
        if (!isPart && _entityManager.TryGetComponent<Content.Shared._Dystopia.Health.Medical.Addiction.AddictionComponent>(target, out var addiction))
        {
            foreach (var (group, settings) in addiction.Groups)
            {
                var stage = addiction.Stages.GetValueOrDefault(group);
                if (stage > 0)
                    AddCondition(Loc.GetString("condition-withdrawal", ("group", Loc.GetString($"addiction-group-{group}")), ("stage", stage)));
                else if (addiction.Levels.GetValueOrDefault(group) >= settings.AddictedLevel)
                    AddCondition(Loc.GetString("condition-addicted", ("group", Loc.GetString($"addiction-group-{group}"))));
            }
        }

        if (!isPart && _entityManager.TryGetComponent<Content.Shared._Dystopia.Health.Medical.Pain.ConsciousnessComponent>(target, out var consciousness)
            && consciousness.Unconscious)
            AddCondition(Loc.GetString("condition-unconscious-blood"));

        if (!humanoid)
            return;

        foreach (var (part, severity) in _wounds.GetWoundableStatesOnBody(target))
        {
            if (isPart && part != _selected)
                continue;

            if (severity == WoundableSeverity.Severed)
            {
                var (type, symmetry) = _body.ConvertTargetBodyPart(part);
                AddCondition(Loc.GetString("condition-body-trauma-Dismemberment",
                    ("targetSymmetry", symmetry != BodyPartSymmetry.None
                        ? Loc.GetString($"condition-target-symmetry-{symmetry}") + " "
                        : ""),
                    ("targetType", Loc.GetString($"condition-target-type-{type}"))));
                continue;
            }

            if (severity >= WoundableSeverity.Critical)
                AddCondition(Loc.GetString($"condition-body-part-{severity}", ("woundable", PartName(part))));

            // Травмы части: кость, органы, вены, нервы
            if (_body.GetTargetedPartEntity(target, part) is not { } traumaPart)
                continue;

            var bone = _traumas.GetBoneSeverity(traumaPart, effective: false);
            if (bone != BoneSeverity.Normal)
                AddCondition(Loc.GetString($"condition-body-trauma-BoneDamage-{bone}", ("woundable", PartName(part))));
            if (_entityManager.TryGetComponent<Content.Shared._Dystopia.Health.Medical.Pain.LocalAnesthesiaComponent>(traumaPart, out var local)
                && IoCManager.Resolve<Robust.Shared.Timing.IGameTiming>().CurTime < local.Until)
                AddCondition(Loc.GetString("condition-local-anesthesia", ("woundable", PartName(part))));
            if (_entityManager.HasComponent<BoneSplintedComponent>(traumaPart))
                AddCondition(Loc.GetString("condition-body-splinted", ("woundable", PartName(part))));

            // Кровотечение, повязки, жгут
            var bleeding = 0f;
            var bandaged = false;
            var packed = false;
            foreach (var wound in _wounds.GetWoundableWounds(traumaPart))
            {
                if (!_entityManager.TryGetComponent<Content.Shared._Dystopia.Health.Medical.Bleeding.BleedInflicterComponent>(wound, out var bleed)
                    || !bleed.IsBleeding)
                    continue;

                if (bleed.Bandaged)
                    bandaged = true;
                else
                    bleeding += bleed.BleedingAmount;

                if (!bleed.Bandaged && bleed.PackedFactor < 1f)
                    packed = true;
            }

            if (bleeding > 0)
                AddCondition(Loc.GetString(bleeding >= HeavyBleeding(target) ? "condition-part-bleeding-heavy" : "condition-part-bleeding",
                    ("woundable", PartName(part))));
            if (packed)
                AddCondition(Loc.GetString("condition-part-packed", ("woundable", PartName(part))));
            else if (bandaged)
                AddCondition(Loc.GetString("condition-body-bandaged", ("woundable", PartName(part))));

            if (_entityManager.TryGetComponent<Content.Shared._Dystopia.Health.Medical.Bleeding.TourniquetAppliedComponent>(traumaPart, out var tourniquet))
            {
                var minutes = (int) (IoCManager.Resolve<Robust.Shared.Timing.IGameTiming>().CurTime - tourniquet.AppliedAt).TotalMinutes;
                AddCondition(Loc.GetString("condition-body-tourniquet", ("woundable", PartName(part)), ("minutes", minutes)));
            }

            var reported = new HashSet<string>();
            foreach (var trauma in _traumas.GetWoundableTraumas(traumaPart))
            {
                var type = trauma.Comp.TraumaType.Id;
                if (type == TraumaSystem.OrganDamage.Id && trauma.Comp.TraumaTarget is { } organ && _entityManager.EntityExists(organ))
                {
                    if (reported.Add($"{type}:{organ}"))
                        AddCondition(Loc.GetString("condition-body-trauma-OrganDamage",
                            ("woundable", PartName(part)), ("organ", Identity.Name(organ, _entityManager))));
                }
                else if ((type == TraumaSystem.VeinsDamage.Id || type == TraumaSystem.NerveDamage.Id) && reported.Add(type))
                {
                    AddCondition(Loc.GetString($"condition-body-trauma-{type}", ("woundable", PartName(part))));
                }
            }
        }
    }

    private FixedPoint2 VitalDamage(EntityUid target)
    {
        var total = FixedPoint2.Zero;
        foreach (var part in new[] { TargetBodyPart.Head, TargetBodyPart.Chest, TargetBodyPart.Groin })
        {
            if (_body.GetTargetedPartEntity(target, part) is { } partId &&
                _entityManager.TryGetComponent<WoundableComponent>(partId, out var woundable))
            {
                total += _wounds.GetWoundableSeverityPoint(partId, woundable);
            }
        }

        return total;
    }

    private Dictionary<string, FixedPoint2> GroupBy(Dictionary<string, FixedPoint2> perType)
    {
        var groups = new Dictionary<string, FixedPoint2>();
        foreach (var (type, value) in perType)
        {
            if (_wounds.GetDamageGroupByType(type) is not { } group)
                continue;
            groups[group.ID] = groups.GetValueOrDefault(group.ID) + value;
        }

        return groups.OrderByDescending(g => g.Value).ToDictionary(g => g.Key, g => g.Value);
    }

    // ===================== Органы =====================

    private void PopulateOrgans(EntityUid target)
    {
        ReturnButton.Visible = false;
        PartNameLabel.Visible = false;
        DamageLabelHeading.Visible = false;
        DamageLabel.Visible = false;
        DamageLabelHeadingVital.Visible = false;
        DamageLabelVital.Visible = false;

        foreach (var (organ, _) in _body.GetBodyOrgans(target))
        {
            var organName = Identity.Name(organ, _entityManager);

            var capacity = 100;
            var severity = OrganSeverity.Normal;
            if (_entityManager.TryGetComponent<OrganIntegrityComponent>(organ, out var integrity) && integrity.IntegrityCap > 0)
            {
                capacity = (int) Math.Round((integrity.Integrity / integrity.IntegrityCap * 100).Float());
                severity = integrity.Severity;
            }

            GroupsContainer.AddChild(new Label
            {
                Text = Loc.GetString("group-organ-status", ("organ", organName), ("capacity", capacity)),
                Margin = new Thickness(0, 4, 0, 0),
            });

            if (_entityManager.HasComponent<RottingComponent>(organ))
                AddCondition(Loc.GetString("condition-organ-rotting", ("organ", organName)));

            AddCondition(Loc.GetString($"condition-organ-damage-{severity}", ("organ", organName)));
        }
    }

    // ===================== Химикаты =====================

    private void PopulateChemicals(EntityUid target)
    {
        ReturnButton.Visible = false;
        PartNameLabel.Visible = false;
        DamageLabelHeading.Visible = false;
        DamageLabel.Visible = false;
        DamageLabelHeadingVital.Visible = false;
        DamageLabelVital.Visible = false;

        var owners = new List<EntityUid> { target };
        foreach (var organ in _organs.EnumerateOrgans<Content.Shared.Body.OrganComponent>(target))
        {
            owners.Add(organ.Owner);
        }

        foreach (var owner in owners)
        {
            foreach (var (name, solution) in _solutions.EnumerateSolutions(owner))
            {
                // «food» — это сами органы как мясо (их можно съесть), а не химикаты в пациенте
                if (name != null && HiddenSolutions.Contains(name))
                    continue;

                var contents = solution.Comp.Solution.Contents;
                if (contents.Count == 0)
                    continue;

                var title = name == null
                    ? Loc.GetString("group-solution-unknown")
                    : Loc.TryGetString($"group-solution-name-{name}", out var localized) ? localized : name;

                GroupsContainer.AddChild(new Label
                {
                    Text = Loc.GetString("group-solution-name", ("solution", title)),
                    Margin = new Thickness(0, 6, 0, 0),
                    StyleClasses = { "LabelHeading" },
                });

                foreach (var reagent in contents)
                {
                    string reagentName = _prototypes.TryIndex<ReagentPrototype>(reagent.Reagent.Prototype, out var proto)
                        ? proto.LocalizedName
                        : reagent.Reagent.Prototype.Id;

                    GroupsContainer.AddChild(new Label
                    {
                        Text = " · " + Loc.GetString("group-solution-contents", ("reagent", reagentName), ("quantity", reagent.Quantity)),
                    });
                }
            }
        }
    }

    // ===================== Общее =====================

    private void AddCondition(string text)
    {
        ConditionsListContainer.AddChild(new RichTextLabel { Text = text, Margin = new Thickness(0, 4) });
    }

    private string PartName(TargetBodyPart part)
    {
        var (type, symmetry) = _body.ConvertTargetBodyPart(part);
        return Loc.GetString($"part-status-part-{type}-{symmetry}");
    }

    private static string GetStatus(MobState mobState) => mobState switch
    {
        MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
        MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
        MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
        _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
    };

    private void DrawDiagnosticGroups(Dictionary<string, FixedPoint2> groups, Dictionary<string, FixedPoint2> damageDict)
    {
        foreach (var (groupId, amount) in groups)
        {
            if (amount == 0 || !_prototypes.TryIndex<DamageGroupPrototype>(groupId, out var group))
                continue;

            var container = new BoxContainer { Orientation = LayoutOrientation.Vertical };
            var title = new BoxContainer
            {
                Margin = new Thickness(0, 6, 0, 0),
                VerticalAlignment = VAlignment.Bottom,
                Orientation = LayoutOrientation.Horizontal,
            };
            title.AddChild(new TextureRect { SetSize = new Vector2(30, 30), Texture = GetTexture(groupId.ToLower()) });
            title.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-damage-group-text",
                    ("damageGroup", group.LocalizedName), ("amount", amount)),
            });
            container.AddChild(title);

            foreach (var type in group.DamageTypes)
            {
                if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                    continue;

                container.AddChild(new Label
                {
                    Text = " · " + Loc.GetString("health-analyzer-window-damage-type-text",
                        ("damageType", _prototypes.Index<DamageTypePrototype>(type).LocalizedName), ("amount", typeAmount)),
                });
            }

            GroupsContainer.AddChild(container);
        }
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);
        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out _))
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");

        return _spriteSystem.Frame0(rsiSprite);
    }

    private float HeavyBleeding(EntityUid target)
    {
        return _entityManager.TryGetComponent<Content.Shared._Dystopia.Health.Medical.Bleeding.WoundBleedingComponent>(target, out var bleeding)
            ? bleeding.HeavyBleeding
            : 1.5f;
    }

    /// <summary>Растворы, которые не показываем: съедобность органов и служебные.</summary>
    private static readonly HashSet<string> HiddenSolutions = new() { "food", "bloodstreamTemporary" };

    private static bool SpriteViewAllowed(HealthAnalyzerUiState state) => state.ScanMode is true;

    private static string HoverName(TargetBodyPart part) => part switch
    {
        TargetBodyPart.Head => "head",
        TargetBodyPart.Chest => "torso",
        TargetBodyPart.Groin => "groin",
        TargetBodyPart.LeftArm => "leftarm",
        TargetBodyPart.LeftHand => "lefthand",
        TargetBodyPart.RightArm => "rightarm",
        TargetBodyPart.RightHand => "righthand",
        TargetBodyPart.LeftLeg => "leftleg",
        TargetBodyPart.LeftFoot => "leftfoot",
        TargetBodyPart.RightLeg => "rightleg",
        TargetBodyPart.RightFoot => "rightfoot",
        _ => "torso",
    };
}
