// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._Dystopia.Health.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Dystopia.Health.UserInterface.Systems.Targeting.Widgets;

[GenerateTypedNameReferences]
public sealed partial class TargetingControl : UIWidget
{
    private readonly TargetingUIController _controller;
    private readonly IResourceCache _resCache;
    private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartControls;

    public TargetingControl()
    {
        RobustXamlLoader.Load(this);
        _controller = UserInterfaceManager.GetUIController<TargetingUIController>();
        _resCache = IoCManager.Resolve<IResourceCache>();

        _bodyPartControls = new Dictionary<TargetBodyPart, TextureButton>
        {
            // TODO: ADD EYE AND MOUTH TARGETING
            { TargetBodyPart.Head, HeadButton },
            { TargetBodyPart.Chest, ChestButton },
            { TargetBodyPart.Groin, GroinButton },
            { TargetBodyPart.LeftArm, LeftArmButton },
            { TargetBodyPart.LeftHand, LeftHandButton },
            { TargetBodyPart.RightArm, RightArmButton },
            { TargetBodyPart.RightHand, RightHandButton },
            { TargetBodyPart.LeftLeg, LeftLegButton },
            { TargetBodyPart.LeftFoot, LeftFootButton },
            { TargetBodyPart.RightLeg, RightLegButton },
            { TargetBodyPart.RightFoot, RightFootButton },
        };

        foreach (var bodyPartButton in _bodyPartControls)
        {
            bodyPartButton.Value.MouseFilter = MouseFilterMode.Stop;
            bodyPartButton.Value.OnPressed += _ => SetActiveBodyPart(bodyPartButton.Key);

            // Dystopia: подсветка части при наведении — текстурой кнопки (без правок таблиц стилей)
            var button = bodyPartButton.Value;
            var hover = _resCache.GetResource<TextureResource>($"/Textures/_Dystopia/Health/Interface/Targeting/Doll/{HoverName(bodyPartButton.Key)}_hover.png").Texture;
            button.OnMouseEntered += _ => button.TextureNormal = hover;
            button.OnMouseExited += _ => button.TextureNormal = null;

            TargetDoll.Texture = Theme.ResolveTexture("target_doll");
        }
    }

    private void SetActiveBodyPart(TargetBodyPart bodyPart) => _controller.CycleTarget(bodyPart);

    private static string HoverName(TargetBodyPart part) => part switch
    {
        TargetBodyPart.Head => "head",
        TargetBodyPart.Chest => "torso",
        TargetBodyPart.Groin => "groin",
        TargetBodyPart.LeftArm => "leftarm",
        TargetBodyPart.LeftHand => "lefthand",
        TargetBodyPart.RightArm => "rightarm",
        TargetBodyPart.RightHand => "righthand",
        TargetBodyPart.LeftLeg => "leftleg",
        TargetBodyPart.LeftFoot => "leftfoot",
        TargetBodyPart.RightLeg => "rightleg",
        TargetBodyPart.RightFoot => "rightfoot",
        _ => "torso",
    };

    public void SetBodyPartsVisible(TargetBodyPart bodyPart)
    {
        foreach (var bodyPartButton in _bodyPartControls)
            bodyPartButton.Value.Children.First().Visible = bodyPartButton.Key == bodyPart;
    }

    protected override void OnThemeUpdated() => TargetDoll.Texture = Theme.ResolveTexture("target_doll");

    public void SetTargetDollVisible(bool visible) => Visible = visible;

}